name: local dockerized action
on: push

jobs:
  warn:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Containerized Build
      uses: ./.github/actions/my-container-action
